# Generated by Django 5.1.1 on 2024-11-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('enum_status', models.CharField(choices=[('good', 'Good'), ('reconstruction', 'Reconstruction')], max_length=50)),
                ('pin', models.BooleanField(default=False)),
                ('ai_status', models.CharField(choices=[('good', 'Good'), ('reconstruction', 'Reconstruction')], max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('commit', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
