# Generated by Django 5.1.1 on 2024-11-12 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_record_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ai_status',
            field=models.CharField(choices=[('good', 'Good'), ('reconstruction', 'Reconstruction')], default='good', help_text='AI assessment status', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional comments for the record', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='commit',
            field=models.BooleanField(default=False, help_text='Commit status of the record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='enum_status',
            field=models.CharField(choices=[('good', 'Good'), ('reconstruction', 'Reconstruction')], default='good', help_text='Status of the record', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(help_text='Upload an image for the record', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='pin',
            field=models.BooleanField(default=False, help_text='Indicates whether a PIN is set for the record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_number',
            field=models.IntegerField(help_text='Unique serial number for the record', unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(blank=True, help_text='Additional status information', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(help_text='User associated with this record', on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
    ]
